import platform; print(platform.platform())
import sys; print("system",sys.version)
import numpy; print("Numpy", numpy.__version__)
import pandas; print("pandas", pandas.__version__)
import scipy; print("scipy", scipy.__version__)
import sklearn; print("sklearn", sklearn.__version__)
import xgboost; print("XGboost", xgboost.__version__)